using System.Text.Json;
using PadKit.Designer;
using PadKit.Flow;

// padkit — PAD フローテキストの生成 (render) / 検査 (lint) / デザイナー操作 (designer)
// exit code: 0 = 正常, 1 = findings/検査失敗, 2 = 使い方/実行エラー

var opts = new Opts(args);
if (opts.Positional.Count == 0)
{
    Console.Error.WriteLine(Usage());
    return 2;
}

try
{
    return opts.Positional[0] switch
    {
        "render" => CmdRender(opts),
        "render-all" => CmdRenderAll(opts),
        "lint" => CmdLint(opts),
        "blocks" => CmdBlocks(opts),
        "designer" => CmdDesigner(opts),
        _ => UsageError($"不明なコマンド: {opts.Positional[0]}"),
    };
}
catch (RenderException ex)
{
    Console.Error.WriteLine(ex.Message);
    return 1;
}
catch (PadDesignerException ex)
{
    Console.Error.WriteLine(ex.Message);
    return 2;
}
catch (Exception ex) when (ex is IOException or InvalidDataException or ArgumentException)
{
    Console.Error.WriteLine(ex.Message);
    return 2;
}

int CmdRender(Opts o)
{
    var recipe = o.RequirePositional(1, "render <recipe.pad>");
    var profile = LoadProfile(o);
    var blocks = BlockResolver.Create(Path.GetDirectoryName(Path.GetFullPath(recipe)), o.Multi("blocks"));
    var result = Renderer.Render(File.ReadAllText(recipe), profile, blocks,
        new RenderOptions
        {
            GeneratedHeader = $"# generated by padkit from {Path.GetFileName(recipe)}" +
                $" --profile {profile.Name}; do not edit by hand",
        });
    WriteDiagnostics(result.Diagnostics);
    var rules = LoadRules(o);
    var findings = Linter.Lint(result.Text, rules)
        .Concat(result.Subflows.SelectMany(s => Linter.Lint(s.Text, rules))).ToList();
    WriteFindings(findings, o.Json);
    if (o.Get("out") is { } outFile)
        WriteOutputs(result, outFile);
    else
        Console.Out.Write(result.Text);
    return findings.Any(f => f.Severity == Severity.Error) ? 1 : 0;
}

/// <summary>メインを outFile に、各サブフローを &lt;base&gt;.&lt;Name&gt;.txt として同じ dir に書く。</summary>
static List<string> WriteOutputs(RenderResult result, string outFile)
{
    var written = new List<string> { outFile };
    File.WriteAllText(outFile, result.Text);
    var basePath = outFile.EndsWith(".txt", StringComparison.OrdinalIgnoreCase)
        ? outFile[..^4] : outFile;
    foreach (var sub in result.Subflows)
    {
        var p = $"{basePath}.{sub.Name}.txt";
        File.WriteAllText(p, sub.Text);
        written.Add(p);
    }
    return written;
}

int CmdRenderAll(Opts o)
{
    var dir = o.RequirePositional(1, "render-all <recipes-dir>");
    var profile = LoadProfile(o);
    var outDir = o.RequireOption("out-dir");
    Directory.CreateDirectory(outDir);
    var blocks = BlockResolver.Create(Path.GetFullPath(dir), o.Multi("blocks"));
    var failed = false;
    foreach (var recipe in Directory.EnumerateFiles(dir, "*.pad").OrderBy(f => f))
    {
        var name = Path.GetFileNameWithoutExtension(recipe);
        try
        {
            var result = Renderer.Render(File.ReadAllText(recipe), profile, blocks,
                new RenderOptions
                {
                    GeneratedHeader = $"# generated by padkit from recipes/{name}.pad" +
                        $" --profile {profile.Name}; do not edit by hand",
                });
            var rules = LoadRules(o);
            var findings = Linter.Lint(result.Text, rules)
                .Concat(result.Subflows.SelectMany(s => Linter.Lint(s.Text, rules))).ToList();
            foreach (var f in findings)
                Console.Error.WriteLine($"{name}:{f.Line} {f.RuleId} {f.Message}");
            var written = WriteOutputs(result, Path.Combine(outDir, name + ".txt"));
            Console.Error.WriteLine($"{name}: rendered ({written.Count} file(s))");
            if (findings.Any(f => f.Severity == Severity.Error)) failed = true;
        }
        catch (RenderException ex)
        {
            Console.Error.WriteLine($"{name}: {ex.Message}");
            failed = true;
        }
    }
    return failed ? 1 : 0;
}

int CmdLint(Opts o)
{
    var files = o.Positional.Skip(1).ToList();
    if (files.Count == 0) return UsageError("lint <file>...");
    var rules = LoadRules(o);
    var all = new List<(string File, Finding Finding)>();
    foreach (var file in files)
        foreach (var f in Linter.Lint(File.ReadAllText(file), rules))
            all.Add((file, f));

    if (o.Json)
    {
        Console.WriteLine(JsonSerializer.Serialize(all.Select(x => new
        {
            file = x.File, rule = x.Finding.RuleId, line = x.Finding.Line,
            severity = x.Finding.Severity.ToString().ToLowerInvariant(),
            message = x.Finding.Message, fix = x.Finding.Fix,
        }), JsonOut.Opts));
    }
    else
    {
        foreach (var (file, f) in all)
            Console.WriteLine($"{file}:{f.Line}: {f.RuleId} " +
                $"{f.Severity.ToString().ToLowerInvariant()} {f.Message}" +
                (f.Fix is null ? "" : $" (fix: {f.Fix})"));
        Console.WriteLine($"{all.Count} finding(s)");
    }
    return all.Any(x => x.Finding.Severity == Severity.Error) ? 1 : 0;
}

int CmdBlocks(Opts o)
{
    var blocks = BlockResolver.Create(null, o.Multi("blocks"));
    foreach (var b in blocks.ListAll())
    {
        var pars = string.Join(" ", b.Params.Select(p =>
            p.Required ? $"{p.Name} (必須)" : $"{p.Name} (default=\"{p.Default}\")"));
        Console.WriteLine($"{b.Name}: {pars}  [{b.SourcePath}]");
    }
    return 0;
}

int CmdDesigner(Opts o)
{
    var sub = o.RequirePositional(1, "designer <sub>");
    if (sub == "windows")
    {
        foreach (var w in PadKit.Designer.PadDesigner.ListWindows())
            Console.WriteLine(w);
        return 0;
    }

    using var designer = PadKit.Designer.PadDesigner.Attach();
    Console.Error.WriteLine($"attached: '{designer.WindowTitle}'");
    switch (sub)
    {
        case "status":
            Console.WriteLine($"status={designer.Status()} actions={designer.ActionCount()}" +
                $" errors={designer.ErrorCount()}");
            return 0;
        case "dump":
            Console.WriteLine(designer.Dump(o.GetInt("depth", 14)));
            return 0;
        case "clear":
            designer.ClearAll();
            Console.WriteLine("cleared");
            return 0;
        case "paste":
        {
            var file = o.RequirePositional(2, "designer paste <file>");
            designer.ClearAll();
            designer.Paste(File.ReadAllText(file));
            Console.WriteLine($"pasted: actions={designer.ActionCount()}");
            return 0;
        }
        case "subflows":
            foreach (var n in designer.SubflowNames()) Console.WriteLine(n);
            return 0;
        case "check":
            return DesignerCheck(o, designer);
        case "flow":
            return DesignerFlow(o, designer);
        case "run":
            return DesignerRun(o, designer);
        default:
            return UsageError($"不明な designer サブコマンド: {sub}");
    }
}

int DesignerCheck(Opts o, PadKit.Designer.PadDesigner designer)
{
    var files = o.Positional.Skip(2).ToList();
    if (files.Count == 0) return UsageError("designer check <file>...");
    var results = new List<(string Name, CheckResult R)>();
    foreach (var file in files)
    {
        var r = designer.Check(File.ReadAllText(file));
        results.Add((Path.GetFileName(file), r));
    }
    if (o.Json)
    {
        Console.WriteLine(JsonSerializer.Serialize(results.Select(x => new
        {
            file = x.Name, actions = x.R.Actions, errors = x.R.Errors,
            errorTexts = x.R.ErrorTexts,
        }), JsonOut.Opts));
    }
    else
    {
        foreach (var (name, r) in results)
        {
            Console.WriteLine($"{name}: actions={r.Actions} errors={r.Errors}");
            foreach (var t in r.ErrorTexts)
                Console.WriteLine($"  ! {t}");
        }
    }
    return results.Any(x => x.R.Errors > 0) ? 1 : 0;
}

/// <summary>designer flow &lt;base.txt&gt; — &lt;base&gt;.&lt;Sub&gt;.txt をサブフロータブとして
/// 作成/上書きしてから Main を貼り付け、全体のエラーを検査する。</summary>
int DesignerFlow(Opts o, PadKit.Designer.PadDesigner designer)
{
    var mainFile = o.RequirePositional(2, "designer flow <main.txt>");
    var dir = Path.GetDirectoryName(Path.GetFullPath(mainFile))!;
    var stem = Path.GetFileNameWithoutExtension(mainFile);

    // 兄弟ファイル <stem>.<Sub>.txt をサブフローとして集める
    var subs = Directory.EnumerateFiles(dir, stem + ".*.txt")
        .Select(p => (Name: Path.GetFileNameWithoutExtension(p)[(stem.Length + 1)..], Path: p))
        .OrderBy(x => x.Name).ToList();

    // サブフローは変数未定義のまま貼ると「変数が見つかりません」が出るが、
    // Main (SET 行) を貼ると全体解決される。判定は最後の全体エラー数で行う。
    var existing = designer.SubflowNames();
    foreach (var (name, path) in subs)
    {
        if (!existing.Contains(name))
        {
            designer.CreateSubflow(name);
            Console.Error.WriteLine($"subflow '{name}': created");
        }
        designer.SelectSubflow(name);
        var r = designer.Check(File.ReadAllText(path));
        Console.WriteLine($"{Path.GetFileName(path)} [{name}]: actions={r.Actions} (途中の変数未解決エラーは Main 貼付後に解消)");
    }

    designer.SelectSubflow("Main");
    var main = designer.Check(File.ReadAllText(mainFile));
    Console.WriteLine($"{Path.GetFileName(mainFile)} [Main]: actions={main.Actions} errors={main.Errors}");
    foreach (var t in main.ErrorTexts) Console.WriteLine($"  ! {t}");
    return main.Errors > 0 ? 1 : 0;
}

int DesignerRun(Opts o, PadKit.Designer.PadDesigner designer)
{
    var file = o.RequirePositional(2, "designer run <file>");
    var timeout = TimeSpan.FromSeconds(o.GetInt("timeout", 120));
    var r = designer.Check(File.ReadAllText(file));
    if (o.Json)
        Console.WriteLine(JsonSerializer.Serialize(
            new { check = new { actions = r.Actions, errors = r.Errors, errorTexts = r.ErrorTexts } },
            JsonOut.Opts));
    else
    {
        Console.WriteLine($"{Path.GetFileName(file)}: actions={r.Actions} errors={r.Errors}");
        foreach (var t in r.ErrorTexts)
            Console.WriteLine($"  ! {t}");
    }
    if (r.Actions == 0 || r.Errors > 0)
    {
        Console.Error.WriteLine(
            r.Actions == 0 ? "SKIP-RUN (paste produced 0 actions)" : "SKIP-RUN (errors present)");
        return 2;
    }
    designer.Save();
    var run = designer.Run(timeout);
    if (o.Json)
        Console.WriteLine(JsonSerializer.Serialize(new
        {
            started = run.Started, finished = run.Finished,
            lastStatus = run.LastStatus, elapsedSec = run.Elapsed.TotalSeconds,
        }, JsonOut.Opts));
    else
        Console.WriteLine($"run: started={run.Started} finished={run.Finished}" +
            $" status={run.LastStatus} elapsed={run.Elapsed.TotalSeconds:F1}s");
    return run.Finished ? 0 : 1;
}

Profile LoadProfile(Opts o)
{
    var paths = o.Multi("profile");
    if (paths.Count == 0)
        throw new ArgumentException("--profile を 1 つ以上指定してください (複数回指定で後勝ちオーバーレイ)");
    return Profile.Load(paths);
}

RuleSet LoadRules(Opts o)
{
    if (o.Get("rules") is { } p) return RuleSet.Load(p);
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null)
    {
        var candidate = Path.Combine(dir.FullName, "rules", "pad-11.2609.json");
        if (File.Exists(candidate)) return RuleSet.Load(candidate);
        dir = dir.Parent;
    }
    throw new InvalidDataException(
        "ルールファイルが見つかりません (--rules で指定するか padkit 配下の rules/ を配置)");
}

void WriteDiagnostics(IReadOnlyList<Diagnostic> ds)
{
    foreach (var d in ds)
        Console.Error.WriteLine($"{d.Code} (行 {d.Line}) {d.Severity}: {d.Message}");
}

void WriteFindings(IReadOnlyList<Finding> findings, bool json)
{
    foreach (var f in findings)
        Console.Error.WriteLine($"lint {f.Line}: {f.RuleId} {f.Severity} {f.Message}");
}

int UsageError(string msg)
{
    Console.Error.WriteLine(msg);
    Console.Error.WriteLine(Usage());
    return 2;
}

static string Usage() => """
    usage: padkit <command>
      render <recipe.pad> --profile <p.json> [--profile <p2.json>]... [--out <file>] [--blocks <dir>]...
      render-all <dir> --profile <p.json> [--profile <p2.json>]... --out-dir <dir> [--blocks <dir>]
      lint <file>... [--rules <json>] [--json]
      blocks [--blocks <dir>]
      designer windows|status|subflows|dump [--depth N]|clear|paste <file>|check <file>...|flow <main.txt>|run <file> [--timeout N] [--json]
    """;

static class JsonOut
{
    public static readonly JsonSerializerOptions Opts = new() { WriteIndented = false };
}

/// <summary>本 CLI と同形式の素朴な引数パーサ。</summary>
sealed class Opts
{
    public List<string> Positional { get; } = new();
    private readonly Dictionary<string, List<string>> _opts = new(StringComparer.OrdinalIgnoreCase);

    public Opts(string[] argv)
    {
        for (var i = 0; i < argv.Length; i++)
        {
            var a = argv[i];
            if (a.StartsWith("--"))
            {
                var key = a[2..];
                if (!_opts.TryGetValue(key, out var list))
                    _opts[key] = list = new List<string>();
                if (i + 1 < argv.Length && !argv[i + 1].StartsWith("--"))
                    list.Add(argv[++i]);
                else
                    list.Add("true");
            }
            else
            {
                Positional.Add(a);
            }
        }
    }

    public string? Get(string key) =>
        _opts.TryGetValue(key, out var v) ? v.FirstOrDefault() : null;

    public IReadOnlyList<string> Multi(string key) =>
        _opts.TryGetValue(key, out var v) ? v : Array.Empty<string>();

    public bool Json => _opts.ContainsKey("json");

    public int GetInt(string key, int fallback) =>
        int.TryParse(Get(key), out var n) ? n : fallback;

    public string RequirePositional(int index, string usage)
    {
        if (Positional.Count <= index)
            throw new ArgumentException($"引数が足りません: {usage}");
        return Positional[index];
    }

    public string RequireOption(string key) =>
        Get(key) ?? throw new ArgumentException($"--{key} が必要です");
}
