using System.Text.Json;
using PadKit.Flow;

namespace PadKit.Tests;

public class RendererTests
{
    private static Profile MakeProfile(Dictionary<string, object> values)
    {
        var dict = new Dictionary<string, JsonElement>();
        foreach (var (k, v) in values)
            dict[k] = JsonSerializer.SerializeToElement(v);
        return new Profile(dict, "test");
    }

    private static BlockResolver EmptyBlocks() => new(Array.Empty<string>());

    private static BlockResolver DirBlocks(string dir) => new(new[] { dir });

    [Fact]
    public void Requires_Header_EmittedInOrder_WithBackslashDoubling_AndNumericPassthrough()
    {
        var recipe = "# ヘッダ\n#! requires: ExePath Count\nSET X TO 1\n";
        var profile = MakeProfile(new()
        {
            ["ExePath"] = @"C:\tools\mytool\mytool.exe",
            ["Count"] = 3,
        });
        var result = Renderer.Render(recipe, profile, EmptyBlocks());
        var lines = result.Text.Replace("\r\n", "\n").Split('\n');
        Assert.Equal("# ヘッダ", lines[0]);
        Assert.Equal("SET ExePath TO $'''C:\\\\tools\\\\mytool\\\\mytool.exe'''", lines[1]);
        Assert.Equal("SET Count TO 3", lines[2]);
        Assert.Equal("", lines[3]);
        Assert.Equal("SET X TO 1", lines[4]);
    }

    [Fact]
    public void MissingProfileKeys_ReportedTogether()
    {
        var recipe = "#! requires: A B C\nSET X TO 1\n";
        var ex = Assert.Throws<RenderException>(
            () => Renderer.Render(recipe, MakeProfile(new() { ["A"] = "x" }), EmptyBlocks()));
        var msg = ex.Diagnostics.Single(d => d.Code == "E_PROFILE").Message;
        Assert.Contains("B", msg);
        Assert.Contains("C", msg);
    }

    [Fact]
    public void Include_InsideIf_KeepsIndentation()
    {
        var dir = NewBlockDir(("hello", "# コメント\nSET V TO 1\n"));
        var recipe = "IF X = 1 THEN\n    {{> hello}}\nEND\n";
        var result = Renderer.Render(recipe, MakeProfile(new()), DirBlocks(dir));
        Assert.Contains("    SET V TO 1", result.Text);
        Assert.Contains("    # コメント", result.Text);
    }

    [Fact]
    public void DefaultParam_Applied_UnknownParam_Error_MissingRequired_Error()
    {
        var dir = NewBlockDir(
            ("dlg", "#! param Title default=\"既定\"\n#! param Body\nTITLE {{Title}} BODY {{Body}}\n"));
        var profile = MakeProfile(new());

        var ok = Renderer.Render("{{> dlg Body=\"b\"}}\n", profile, DirBlocks(dir));
        Assert.Contains("TITLE 既定 BODY b", ok.Text);

        Assert.Throws<RenderException>(() =>
            Renderer.Render("{{> dlg Body=\"b\" Nope=\"x\"}}\n", profile, DirBlocks(dir)));

        Assert.Throws<RenderException>(() =>
            Renderer.Render("{{> dlg}}\n", profile, DirBlocks(dir)));
    }

    [Fact]
    public void NestedInclude_DepthLimit()
    {
        var dir = NewBlockDir(("loop", "{{> loop}}\n"));
        Assert.Throws<RenderException>(() =>
            Renderer.Render("{{> loop}}\n", MakeProfile(new()), DirBlocks(dir)));
    }

    [Fact]
    public void UnresolvedParam_IsError()
    {
        var ex = Assert.Throws<RenderException>(() =>
            Renderer.Render("SET X TO {{Missing}}\n", MakeProfile(new()), EmptyBlocks()));
        Assert.Contains(ex.Diagnostics, d => d.Code == "E_UNRESOLVED");
    }

    [Fact]
    public void GeneratedHeaderOption_PrependsComment()
    {
        var result = Renderer.Render("SET X TO 1\n", MakeProfile(new()), EmptyBlocks(),
            new RenderOptions { GeneratedHeader = "# generated by padkit from x.pad" });
        Assert.StartsWith("# generated by padkit from x.pad", result.Text);
    }

    [Fact]
    public void Subflow_Sections_Split_AndMainKeepsCall()
    {
        var recipe = "# ヘッダ\n#! requires: P\nCALL Sub\nSET X TO 1\n" +
            "#! subflow Sub\nSET Y TO 2\n";
        var result = Renderer.Render(recipe, MakeProfile(new() { ["P"] = "v" }), EmptyBlocks());
        Assert.Contains("CALL Sub", result.Text);
        Assert.Contains("SET X TO 1", result.Text);
        Assert.DoesNotContain("SET Y TO 2", result.Text);
        var sub = Assert.Single(result.Subflows);
        Assert.Equal("Sub", sub.Name);
        Assert.Contains("SET Y TO 2", sub.Text);
        Assert.Contains("# subflow: Sub", sub.Text);
    }

    [Fact]
    public void Call_UndefinedSubflow_IsError()
    {
        var ex = Assert.Throws<RenderException>(() =>
            Renderer.Render("CALL Nope\n", MakeProfile(new()), EmptyBlocks()));
        Assert.Contains(ex.Diagnostics, d => d.Code == "E_SUBFLOW");
    }

    [Fact]
    public void DeclaredSubflow_NeverCalled_IsWarning()
    {
        var result = Renderer.Render("#! subflow Idle\nSET Y TO 1\n",
            MakeProfile(new()), EmptyBlocks());
        Assert.Contains(result.Diagnostics,
            d => d.Code == "W_SUBFLOW" && d.Severity == Severity.Warning);
    }

    [Fact]
    public void Subflow_IncludeExpandsInsideSection()
    {
        var dir = NewBlockDir(("hello", "SET V TO 1\n"));
        var recipe = "CALL S\n#! subflow S\n{{> hello}}\n";
        var result = Renderer.Render(recipe, MakeProfile(new()), DirBlocks(dir));
        Assert.Contains("SET V TO 1", result.Subflows[0].Text);
    }

    private static string NewBlockDir(params (string Name, string Body)[] blocks)
    {
        var dir = Path.Combine(Path.GetTempPath(), "padkit-test-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        foreach (var (name, body) in blocks)
            File.WriteAllText(Path.Combine(dir, name + ".pad"), body);
        return dir;
    }
}
