using System.Text.Json;
using System.Text.RegularExpressions;

namespace PadKit.Flow;

public sealed class RenderOptions
{
    /// <summary>先頭に付ける生成ヘッダ行 (例: "# generated by padkit ...")。null なら付けない。</summary>
    public string? GeneratedHeader { get; init; }
}

/// <summary>`.pad` レシピ (PAD テキスト + `#!` ディレクティブ + `{{> include}}`) を
/// PAD デザイナーに貼り付け可能なプレーンテキストへ展開する。</summary>
public static class Renderer
{
    public const int MaxIncludeDepth = 8;

    private static readonly Regex RequiresDirective =
        new(@"^#!\s*requires:\s*(?<keys>.*)$", RegexOptions.Compiled);

    private static readonly Regex IncludeLine =
        new(@"^(?<indent>\s*)\{\{>\s*(?<name>[A-Za-z0-9_-]+)(?<args>(?:\s+[A-Za-z_][A-Za-z0-9_]*=""(?:[^""\\]|\\.)*"")*)\s*\}\}\s*$",
            RegexOptions.Compiled);

    private static readonly Regex ArgPair =
        new(@"([A-Za-z_][A-Za-z0-9_]*)=""(?<v>(?:[^""\\]|\\.)*)""", RegexOptions.Compiled);

    private static readonly Regex ParamRef =
        new(@"\{\{\s*(?<key>[A-Za-z_][A-Za-z0-9_]*)\s*\}\}", RegexOptions.Compiled);

    public static RenderResult Render(string recipeText, Profile profile, BlockResolver blocks,
        RenderOptions? options = null)
    {
        var diagnostics = new List<Diagnostic>();
        var output = RenderCore(recipeText, profile, blocks, diagnostics, options);
        var errors = diagnostics.Where(d => d.Severity == Severity.Error).ToList();
        if (errors.Count > 0)
            throw new RenderException(diagnostics);
        return new RenderResult(output, diagnostics);
    }

    private static string RenderCore(string recipeText, Profile profile, BlockResolver blocks,
        List<Diagnostic> diagnostics, RenderOptions? options)
    {
        var lines = SplitLines(recipeText);
        var result = new List<string>();

        if (options?.GeneratedHeader is { } header)
            result.Add(header.StartsWith('#') ? header : "# " + header);

        // 先頭の連続コメント行がヘッダ。`#!` ディレクティブはここでだけ意味を持つ。
        var requiredKeys = new List<string>();
        var i = 0;
        for (; i < lines.Count; i++)
        {
            var line = lines[i];
            if (!line.StartsWith('#')) break;
            var req = RequiresDirective.Match(line);
            if (req.Success)
            {
                requiredKeys.AddRange(req.Groups["keys"].Value
                    .Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
                continue; // ディレクティブ行は出力へ残さない
            }
            result.Add(line);
        }

        // `#!` で始まる行は以降もディレクティブとして落とす
        var bodyLines = lines.Skip(i).Where(l => !l.StartsWith("#!")).ToList();

        // requires の SET 行をヘッダ直後へ差し込む
        if (requiredKeys.Count > 0)
        {
            var missing = requiredKeys.Where(k => !profile.TryGet(k, out _)).ToList();
            if (missing.Count > 0)
            {
                diagnostics.Add(new Diagnostic("E_PROFILE", 0, Severity.Error,
                    $"プロファイル '{profile.Name}' にキーがありません: {string.Join(" ", missing)}"));
            }
            else
            {
                foreach (var key in requiredKeys)
                {
                    profile.TryGet(key, out var v);
                    result.Add($"SET {key} TO {FormatValue(key, v)}");
                }
                result.Add("");
            }
        }

        // include 展開 (深さ 0 から)
        ExpandLines(bodyLines, blocks, indent: "", depth: 0,
            values: new Dictionary<string, string>(), result, diagnostics);

        // 残った {{...}} は未解決パラメータ
        for (var n = 0; n < result.Count; n++)
        {
            if (ParamRef.IsMatch(result[n]) || result[n].Contains("{{"))
                diagnostics.Add(new Diagnostic("E_UNRESOLVED", n + 1, Severity.Error,
                    $"未解決の '{{{{...}}}}' があります: {result[n].Trim()}"));
        }

        return string.Join(Environment.NewLine, result);
    }

    private static void ExpandLines(IReadOnlyList<string> lines, BlockResolver blocks,
        string indent, int depth, IReadOnlyDictionary<string, string> values,
        List<string> output, List<Diagnostic> diagnostics)
    {
        if (depth > MaxIncludeDepth)
        {
            diagnostics.Add(new Diagnostic("E_DEPTH", 0, Severity.Error,
                $"include の深さが上限 {MaxIncludeDepth} を超えました (循環参照の可能性)"));
            return;
        }

        foreach (var rawLine in lines)
        {
            // include 行は引数値をパースしてからパラメータ置換する
            // (先に置換すると値中の '"' が引数区切りを壊す)
            var m = IncludeLine.Match(rawLine);
            if (!m.Success)
            {
                output.Add(indent + Substitute(rawLine, values));
                continue;
            }

            var name = m.Groups["name"].Value;
            var block = blocks.Resolve(name);
            if (block is null)
            {
                diagnostics.Add(new Diagnostic("E_BLOCK", 0, Severity.Error,
                    $"ブロック '{name}' が見つかりません (探索先: {string.Join(", ", blocks.Dirs)})"));
                continue;
            }

            // 引数を組み立てる (default 適用 → 必須チェック → 未知引数チェック)
            var given = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (Match am in ArgPair.Matches(m.Groups["args"].Value))
            {
                var raw = am.Groups["v"].Value;
                given[am.Groups[1].Value] = Substitute(
                    raw.Replace("\\\"", "\"").Replace("\\\\", "\\"), values);
            }

            var unknown = given.Keys.Where(k => block.Params.All(p => p.Name != k)).ToList();
            if (unknown.Count > 0)
            {
                diagnostics.Add(new Diagnostic("E_PARAM", 0, Severity.Error,
                    $"ブロック '{name}' に未知の引数: {string.Join(", ", unknown)}"));
                continue;
            }
            var missingReq = block.Params.Where(p => p.Required && !given.ContainsKey(p.Name)).ToList();
            if (missingReq.Count > 0)
            {
                diagnostics.Add(new Diagnostic("E_PARAM", 0, Severity.Error,
                    $"ブロック '{name}' の必須引数が未指定: {string.Join(", ", missingReq.Select(p => p.Name))}"));
                continue;
            }

            var inner = new Dictionary<string, string>(given, StringComparer.Ordinal);
            foreach (var p in block.Params)
                if (!inner.ContainsKey(p.Name) && p.Default is { } d)
                    inner[p.Name] = d;

            ExpandLines(block.Body, blocks, indent + m.Groups["indent"].Value, depth + 1,
                inner, output, diagnostics);
        }
    }

    private static string Substitute(string text, IReadOnlyDictionary<string, string> values) =>
        values.Count == 0 ? text
            : ParamRef.Replace(text, mm =>
                values.TryGetValue(mm.Groups["key"].Value, out var v) ? v : mm.Value);

    private static string FormatValue(string key, JsonElement v) => v.ValueKind switch
    {
        JsonValueKind.String =>
            $"$'''{v.GetString()!.Replace("\\", "\\\\")}'''",
        JsonValueKind.Number or JsonValueKind.True or JsonValueKind.False =>
            v.GetRawText(),
        _ => throw new RenderException(new[]
        {
            new Diagnostic("E_PROFILE", 0, Severity.Error,
                $"キー '{key}' の値は string/number/bool のみ使えます ({v.ValueKind})"),
        }),
    };

    private static List<string> SplitLines(string text) =>
        text.Replace("\r\n", "\n").Split('\n')
            .Select(l => l.TrimEnd('\r')).ToList();
}
